# Generated by Django 6.0 on 2026-04-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('original_size', models.FloatField(blank=True, null=True)),
                ('compressed_size', models.FloatField(blank=True, null=True)),
                ('compression_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
